---
- name: deploy gobble on EC2
  hosts: all
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
    - name: Install utilities
      become: yes
      become_user: root
      ansible.builtin.apt:
        pkg:
        - unzip

    - name: Add nodejs apt key
      become: yes
      become_user: root
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add nodejs 18.x ppa for apt repo
      become: yes
      become_user: root
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x focal main
        update_cache: yes

    - name: Install nodejs
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: nodejs

    - name: get latest github repo
      git:
        repo: https://github.com/transitmatters/gobble.git
        dest: /home/ubuntu/gobble
        force: yes

    - name: copy config file
      copy:
        src: local.json
        dest: /home/ubuntu/gobble/config/local.json

    - name: copy systemd service file
      become: yes
      become_user: root
      copy:
        src: systemd.conf
        dest: /etc/systemd/system/gobble.service

    - name: install app dependencies
      shell: npm ci
      args:
        chdir: /home/ubuntu/gobble

    - name: build application
      shell: npm run build
      args:
        chdir: /home/ubuntu/gobble

    - name: Download and unzip MBTA static GTFS
      unarchive:
        src: https://cdn.mbta.com/MBTA_GTFS.zip
        dest: /home/ubuntu
        remote_src: yes

    - name: restart service
      become: yes
      become_user: root
      shell: systemctl restart gobble
