[tool.poetry]
name = "gobble"
version = "1.0.0"
description = ""
authors = ["TransitMatters Labs <labs@transitmatters.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
pandas = "2.1.3"
sseclient-py = "1.8.0"
requests = "2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
